import org.wso2.carbon.billing.core.dataobjects.Customer;
import org.wso2.carbon.billing.core.dataobjects.Invoice;
import org.wso2.carbon.billing.core.dataobjects.Cash;

rule customerOneSpecial
when
$customer : Customer(name == "customer-1" )

then

Invoice invoice = $customer.getActiveInvoice();
Cash total = invoice.getTotalCost();
invoice.setTotalCost(Cash.subtract(total, new Cash("$1")));

end
