#!/bin/bash
# ----------------------------------------------------------------------------
#
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.
#
# ----------------------------------------------------------------------------

INSTANCE=$1
INSTANCE_USER=$2
KEY=$3
SOFTWARE=$4

SCP="scp -i ./$KEY"
SSH="ssh -i ./$KEY"

$SCP ./wso2-cartridge-init.sh $INSTANCE_USER@$INSTANCE:
$SCP ./mysql.ctrg $INSTANCE_USER@$INSTANCE:
$SCP ./get-launch-params.rb $INSTANCE_USER@$INSTANCE:
$SCP ./cc/ssl-cert-snakeoil.pem $INSTANCE_USER@$INSTANCE:
$SCP ./cc/ssl-cert-snakeoil.key $INSTANCE_USER@$INSTANCE:
$SCP ./phpMyAdmin-3.5.6-english.tar.xz $INSTANCE_USER@$INSTANCE:

# Copy additional software
arr=$(echo $SOFTWARE | tr ":" "\n")
for x in $arr
do
   $SCP $x $INSTANCE_USER@$INSTANCE:
done

# Execute the cartridge creation process in the remoter server
$SSH $INSTANCE_USER@$INSTANCE "sudo chmod 755 ./mysql.ctrg;sudo ./mysql.ctrg"
