import org.wso2.carbon.billing.core.dataobjects.*;
import org.wso2.carbon.billing.mgt.dataobjects.*;


rule smallSubscription
when
$item: MultitenancyPackage(name == "SMB")
$subItem: Item(parent == $item && name == "subscription")
then
$subItem.setCost(new Cash("$100"));
$subItem.setCreditLimit(new Cash("$200"));
end


rule mediumSubscription
when
$item: MultitenancyPackage(name == "Professional")
$subItem: Item(parent == $item && name == "subscription")
then
$subItem.setCost(new Cash("$500"));
$subItem.setCreditLimit(new Cash("$1000"));
end


rule largeSubscription
when
$item: MultitenancyPackage(name == "Enterprise")
$subItem: Item(parent == $item && name == "subscription")
then
$subItem.setCost(new Cash("$2000"));
$subItem.setCreditLimit(new Cash("$4000"));
end


