/*
 * Licensed to the Apache Software Foundation (ASF) under one 
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 * KIND, either express or implied.  See the License for the 
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.stratos.cloud.controller.domain;

import org.apache.stratos.common.Properties;
import org.apache.stratos.common.Property;
import org.apache.stratos.common.beans.NameValuePair;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

/**
 * Holds information about a Member.
 *
 */
public class MemberContext implements Serializable {

    private static final long serialVersionUID = -388327475844701869L;

    // Cartridge type this member belongs to
    private String cartridgeType;
    // Cluster id of this member
    private String clusterId;
    // Member id generated by cloud controller
    private String memberId;
    // Instance id generated by the IaaS
    private String instanceId;
    // Instance id of the application hierarchy member belongs to
    private String clusterInstanceId;

    // Partition this member is in
    private Partition partition;
    // Default private ip address
    private String defaultPrivateIP;
    // Private ips
    private String[] privateIPs;
    // Default public ip address
    private String defaultPublicIP;
    // Public ips
    private String[] publicIPs;
    // Manually allocated ips
    private String[] allocatedIPs;
    // Member initiated time
    private long initTime;
    // LB cluster id of this member
    private String lbClusterId;
    // Network partition id
    private String networkPartitionId;
    // Member expiry period on the topology
    private long obsoleteExpiryTime;
    // Member obsolete init time
    private long obsoleteInitTime;
    // Instance metadata generated by the IaaS
    private InstanceMetadata instanceMetadata;
    // Properties
    private Properties properties;
    private List<NameValuePair> dynamicPayload;

    public MemberContext(String id, String clusterId, Partition partition) {
        this.memberId = id;
        this.clusterId = clusterId;
        this.setPartition(partition);
        init();
    }
    
    public MemberContext() {
        init();
    }
    
    private void init() {
        this.properties = new Properties();
        this.properties.setProperties(new Property[0]);
    }
    
    public String getMemberId() {
        return memberId;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    public String getClusterId() {
        return clusterId;
    }

    public void setClusterId(String clusterId) {
        this.clusterId = clusterId;
    }

    public String getCartridgeType() {
        return cartridgeType;
    }

    public void setCartridgeType(String cartridgeType) {
        this.cartridgeType = cartridgeType;
    }

    public Partition getPartition() {
        return partition;
    }

    public void setPartition(Partition partition) {
        this.partition = partition;
    }

    public String getDefaultPublicIP() {
        return defaultPublicIP;
    }

    public void setDefaultPublicIP(String defaultPublicIP) {
        this.defaultPublicIP = defaultPublicIP;
    }
    
    public String[] getPublicIPs() {
        return publicIPs;
    }

    public void setPublicIPs(String[] publicIPs) {
        this.publicIPs = publicIPs;
    }

    public String getDefaultPrivateIP() {
        return defaultPrivateIP;
    }

    public void setDefaultPrivateIP(String defaultPrivateIP) {
        this.defaultPrivateIP = defaultPrivateIP;
    }
    
    public String[] getPrivateIPs() {
        return privateIPs;
    }

    public void setPrivateIPs(String[] privateIPs) {
        this.privateIPs = privateIPs;
    }

    public String[] getAllocatedIPs() {
        return allocatedIPs;
    }

    public void setAllocatedIPs(String[] allocatedIPs) {
        this.allocatedIPs = allocatedIPs;
    }

    public long getInitTime() {
        return initTime;
    }

    public void setInitTime(long initTime) {
        this.initTime = initTime;
    }

    public String getLbClusterId() {
        return lbClusterId;
    }

    public void setLbClusterId(String lbClusterId) {
        this.lbClusterId = lbClusterId;
    }

    public String getNetworkPartitionId() {
        return networkPartitionId;
    }

    public void setNetworkPartitionId(String networkPartitionId) {
        this.networkPartitionId = networkPartitionId;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((clusterId == null) ? 0 : clusterId.hashCode());
		result = prime * result
				+ ((memberId == null) ? 0 : memberId.hashCode());
		result = prime * result + ((instanceId == null) ? 0 : instanceId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MemberContext other = (MemberContext) obj;
		if (clusterId == null) {
			if (other.clusterId != null)
				return false;
		} else if (!clusterId.equals(other.clusterId))
			return false;
		if (memberId == null) {
			if (other.memberId != null)
				return false;
		} else if (!memberId.equals(other.memberId))
			return false;
		if (instanceId == null) {
			if (other.instanceId != null)
				return false;
		} else if (!instanceId.equals(other.instanceId))
			return false;
		return true;
	}

	public String getInstanceId() {
		return instanceId;
	}

	public void setInstanceId(String instanceId) {
		this.instanceId = instanceId;
	}

    public long getObsoleteExpiryTime() {
        return obsoleteExpiryTime;
    }

    public void setObsoleteExpiryTime(long obsoleteExpiryTime) {
        this.obsoleteExpiryTime = obsoleteExpiryTime;
    }

    public long getObsoleteInitTime() {
        return obsoleteInitTime;
    }

    public void setObsoleteInitTime(long obsoleteInitTime) {
        this.obsoleteInitTime = obsoleteInitTime;
    }

    public Properties getProperties() {
        return properties;
    }

    public void setProperties(Properties properties) {
        this.properties = properties;
    }

    public InstanceMetadata getInstanceMetadata() {
        return instanceMetadata;
    }

    public void setInstanceMetadata(InstanceMetadata instanceMetadata) {
        this.instanceMetadata = instanceMetadata;
    }

    public void setClusterInstanceId(String clusterInstanceId) {
        this.clusterInstanceId = clusterInstanceId;
    }

    public String getClusterInstanceId() {
        return clusterInstanceId;
    }

    public void setDynamicPayload(List<NameValuePair> dynamicPayload) {
        this.dynamicPayload = dynamicPayload;
    }

    public List<NameValuePair> getDynamicPayload() {
        return dynamicPayload;
    }

    @Override
    public String toString() {
        return "MemberContext [memberId=" + memberId + ", instanceId=" + instanceId
                + ", clusterId=" + clusterId + ", partition=" + partition
                + ", cartridgeType=" + cartridgeType + ", defaultPrivateIP=" + defaultPrivateIP
                + ", defaultPublicIP=" + defaultPublicIP + ", allocatedIPs=" + Arrays.toString(allocatedIPs)
                + ", publicIPs=" + Arrays.toString(publicIPs) + ", privateIPs=" + Arrays.toString(privateIPs)
                + ", initTime=" + initTime + ", lbClusterId=" + lbClusterId
                + ", networkPartitionId=" + networkPartitionId + ", instanceMetadata=" + instanceMetadata +
                ", properties=" + properties + "]";
    }
}
